"""empty message

Revision ID: 18c4f0e138f4
Revises: 78c91cdfd772
Create Date: 2017-08-14 13:35:28.353719

"""

# revision identifiers, used by Alembic.
revision = '18c4f0e138f4'
down_revision = '78c91cdfd772'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('file_id', 'uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###
