"""empty message

Revision ID: 2b09fa23c751
Revises: 915d41989da1
Create Date: 2017-04-04 17:35:33.890443

"""

# revision identifiers, used by Alembic.
revision = '2b09fa23c751'
down_revision = '915d41989da1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('mimetype', sa.Text(), nullable=False,
        server_default=""))
    op.drop_column('files', 'filetype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filetype', sa.VARCHAR(length=5), nullable=False))
    op.drop_column('files', 'mimetype')
    # ### end Alembic commands ###
