"""empty message

Revision ID: 78c91cdfd772
Revises: 2b09fa23c751
Create Date: 2017-04-13 13:27:10.429156

"""

# revision identifiers, used by Alembic.
revision = '78c91cdfd772'
down_revision = '2b09fa23c751'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directories', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'title')
    op.drop_column('directories', 'title')
    # ### end Alembic commands ###
