"""Add pinned to directories and files

Revision ID: e2e671ede5a4
Revises: e99a064326b9
Create Date: 2022-03-25 21:23:44.747992

"""

# revision identifiers, used by Alembic.
revision = 'e2e671ede5a4'
down_revision = 'e99a064326b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directories', sa.Column('pinned', sa.Boolean(), nullable=False, default=False))
    op.add_column('files', sa.Column('pinned', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'pinned')
    op.drop_column('directories', 'pinned')
    # ### end Alembic commands ###
