"""empty message

Revision ID: e99a064326b9
Revises: c5793935c735
Create Date: 2019-09-10 17:33:58.864290

"""

# revision identifiers, used by Alembic.
revision = 'e99a064326b9'
down_revision = 'c5793935c735'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('lockdown', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('lockdown')
    )
    op.add_column('files', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'hidden')
    op.drop_table('admin')
    # ### end Alembic commands ###
